### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#1]
**Value Statement:**
As a customer, I want to be greeted and see at first glance what the page is about.

**Description:**
<img width="320" alt="Screenshot 2021-06-07 at 20 32 29" src="https://user-images.githubusercontent.com/82392827/121071325-171f8a00-c7d0-11eb-89a0-300fad71a83b.png">

**Acceptance criteria:**
_Overall impression: The user should recognize at first glance what this app is about and what he can do on this app _

- [x] The customer should be greeted 
- [x] The logo should be presented to the customer so that he can establish a direct connection to the app and remember it 
- [x] The user should already be presented with the two main functions of the app on this page 
- [x] The user is invited to collect his first blockchain experience on this app and get started right away with a click on a button 

**Complexity:**
M

**Tasks:**
- [x] Create a new feature branch :sparkles: Welcome Page :sparkles:
- [x] Create a Headline
- [x] Create a Logo and place it
- [x] Create two links to the main functions
- [x] Create a paragraph with a link to the news
