### ISSUE TITLE
Top 25 Cryptocurrencies

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#14]

**Comment by bejanaf** [comment]
**Value Statement:**
As a customer, I would like to be shown the top 25 cryptocurrencies and what their current rank is 

**Acceptance criteria:**
- [x] As a user, I would like to see which are the 25 most valuable cryptocurrencies 
- [x] As a user, I would like to see how high the market capitalization of a cryptocurrency is 
- [x] As a user, I would like to see the abbreviation for the cryptocurrency is 
- [x] As a user, I would like to see the price change of a cryptocurrency over the last 24 hours 
- [x] as a user, I would like to see the logo of the cryptocurrency 
- [x] As a user, I would like to be able to add the cryptocurrency to my wallet with a like logo 

**Complexity:**
S

**Tasks:**
- [x] create feature branch ✨ feature-top-25 ✨
- [x] add new Route to TopCoins.js
- [x] add navigation to TopCoins.js
- [x] fetch data from Api
- [x] save data in a useState
- [x] change the data from useState with a useEffect
- [x] map the data to display all needed data
- [x] refactor the top 25 mapped data as a component
