### ISSUE TITLE
localStorage to create Wallet

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#15]
**Value Statement:**
As a customer, I want my favorite Coins to be saved and retained 

**Description:**
In order for the favoring of the different Blockchains to work, the selected Blockchain must be cached locally in the browser with local storage 

**Acceptance criteria:**
- [x] The user should optically recognize that the selected Blockchain is favored by a highlighted icon 
- [x] The favorited Blockchain should be retained despite a restart or refresh of the website

**Complexity:**
m

**Tasks:**
- [x] Create new feature branch :sparkles: feature-local-storage-blockchain :sparkles:
- [x] Add do lib directory 
- [x] fetch the data with useEffect 
- [x] Save to local storage from TopCoins.js
- [x] load on Wallet.js from local storage
- [x] Toggle function on the favorite icon
