### ISSUE TITLE
News Page

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#2]
**Value Statement:**
As a customer, I would like to see the latest blockchain news and have the opportunity to favor them.

**Description:**
![News](https://user-images.githubusercontent.com/82392827/121183300-3536ca00-c864-11eb-8935-2f502e5b23e1.png)

**Acceptance criteria:**
- [x] The topic-relevant heading of the page should be displayed to the user so that he knows where he is and what this page is about 
- [x]  The user should have the title of each new blockchain message highlighted so that he can quickly find messages that are relevant to himself 
- [x] the section of the message under the message heading should only be displayed to a limited extent. The user should only be able to read the first lines so that he has a better overview of the entire message 
- [ ] If the user likes a message, he should be able to use an icon to favor the message 
- [x] the user should be shown the navigation in order to be able to switch between the desired functions 

**Complexity:**
L

**Tasks:**
- [x]  create a new feature branch :sparkles: feature-news-page :sparkles:
- [x] create a headline
- [x] fetch the news from an api (link)
- [ ] create an icon that favors (Bookmark) (link) the news 
- [x] Add the navigation 
- [x] Add add a structured backend

**Comment by bejanaf** [comment]
**Value Statement**
As a customer, I would like to see the latest blockchain news and have the opportunity to favor them.

**Description:**
Wireframe anfertigen!

**Acceptance criteria**
- [ ] The topic-relevant heading of the page should be displayed to the user so that he knows where he is and what this page is about 
- [ ]  The user should have the title of each new blockchain message highlighted so that he can quickly find messages that are relevant to himself 
- [ ] the section of the message under the message heading should only be displayed to a limited extent. The user should only be able to read the first lines so that he has a better overview of the entire message 
- [ ] The user should have the option of folding in and out the entire message via a button 
- [ ] If the user likes a message, he should be able to use an icon to favor the message 
- [ ] the user should be shown the navigation in order to be able to switch between the desired functions 

**Complexity:**
L

**Tasks:**
- [ ]  create a new feature branch :sparkles: feature-news-page :sparkles:
- [ ] create a headline
- [ ] fetch the news from an api (link)
- [ ] create an icon that favors (Bookmark) (link) the news 
- [ ] integrate the navigation
