### ISSUE TITLE
Bookmark Page

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#3]
**Value Statement:**
As a customer, I would like to see all the news on this page that I have noted on the news page 

**Description:**
![Bookmarks](https://user-images.githubusercontent.com/82392827/121190394-4cc58100-c86b-11eb-926f-70a447f6cddb.png)

**Acceptance criteria:**
- [x] The user should get his favorite messages displayed here so that he has quick access to messages that he has noted or those that are important to him 
- [x] With the bookmark icon, the user should be able to remove messages that he no longer wants to be displayed 
- [x] the user should be shown the navigation in order to be able to switch between the desired functions 

**Complexity:**
M

**Tasks:**
- [x]  create a feature branch :sparkles: feature-bookmark :sparkles:
- [x] Create headliner 
- [x] Load from local storage
- [x] Add Bookmark Icon
- [x] Local storage
- [x] Add the navigation

**Comment by bejanaf** [comment]
**Value Statement**
As a customer, I would like to see all the news on this page that I have noted on the news page 

**Description:**
![Bookmarks](https://user-images.githubusercontent.com/82392827/121190394-4cc58100-c86b-11eb-926f-70a447f6cddb.png)

**Acceptance criteria**
- [ ] The user should get his favorite messages displayed here so that he has quick access to messages that he has noted or those that are important to him 
- [ ] With the bookmark icon, the user should be able to remove messages that he no longer wants to be displayed 

**Complexity:**
M

**Tasks:**
- [ ] Create headliner 
- [ ] Load from local storage
- [ ] Add Bookmark Icon
- [ ] Toggle function to display, or remove the bookmarked news
