### ISSUE TITLE
Wallet Page

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#4]
**Value Statement:**
As a customer, I would like to see wallets for coins that I have selected and the value of my purchased coins 

**Description:**
![Wallet](https://user-images.githubusercontent.com/82392827/121193563-3b31a880-c86e-11eb-8e63-5db8a102c065.png)

**Acceptance criteria:**
- [ ] Using a plus button, the user should be able to search for any coin 
- [ ] In the case of a selected coin, the user should be shown the abbreviation of the coin, as well as: 
- [ ] Show (actual) price
- [ ] The user should be able to enter his coin amount
- [ ] The user should see the total value of his investment 
- [ ] The user should get a percentage of how much his investment is up or down 
- [ ] The user should have the option of deleting each wallet that has been created 
- [ ] the user should be shown the navigation in order to be able to switch between the desired functions

**Complexity:**
L

**Tasks:**
- [ ] Create a feature branch :sparkles: feature-wallet :sparkles:
- [ ] Create headline
- [ ] Fetch the data from api
- [ ] Create a search function to select the respective coins 
- [ ] Create self-generating boxes to display the information from the coin and customer in it
- [ ] create a label for price, quantity and value 
- [ ] Create an input field for the purchased amount of a coin 
- [ ] Add the navigation

**Comment by bejanaf** [comment]
**Value Statement**
As a customer, I would like to see wallets for coins that I have selected and the value of my purchased coins 

**Description:**
![Wallet](https://user-images.githubusercontent.com/82392827/121193563-3b31a880-c86e-11eb-8e63-5db8a102c065.png)

**Acceptance criteria**
- [ ] Using a plus button, the user should be able to search for any coin 
- [ ] In the case of a selected coin, the user should be shown the abbreviation of the coin, as well as: 
- [ ] Show (actual) price
- [ ] The user should be able to enter his coin amount
- [ ] The user should see the total value of his investment 
- [ ] The user should get a percentage of how much his investment is up or down 
- [ ] The user should have the option of deleting each wallet that has been created 

**Complexity:**
L

**Tasks:**
- [ ] Create a feature branch :sparkles: feature-wallet :sparkles:
- [ ] Create headline
- [ ] Fetch the data from api
- [ ] Create a search function to select the respective coins 
- [ ] Create self-generating boxes to display the information from the coin and customer in it
- [ ] create a label for price, quantity and value 
- [ ] Create an input field for the purchased amount of a coin
