### ISSUE TITLE
Footer - Navigation

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#5]
**Value Statement:**
As a customer, I want to have a clear navigation with which I can easily switch between the pages 

**Description:**
![Navigation](https://user-images.githubusercontent.com/82392827/121222005-7049f500-c886-11eb-989d-6059254aaebd.png)

**Acceptance criteria:**
The user should see all the icons in order to be able to navigate to each page of the app. This includes: 
- [x] News button as icon
- [x] Bookmark button as icon
- [x] Wallet button as icon
- [x] The user should be able to navigate between the pages using the icons 
- [x] The icon of the active page should be highlighted so that the user can see on which page he is currently moving 

**Complexity:**
S

**Tasks:**
- [x] Create a feature branch :sparkles: feature-navigation :sparkles:
- [x] Npm install react-router-dom
- [x] Create navigation component
- [x] Add icons to navbar
- [x] Connect sites with react-router and navlink
