### ISSUE TITLE
LocalStorage to Bookmark News

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#6]
**Value Statement:**
As a customer, I want my favorite messages to be saved and retained 

**Description:**
In order for the favoring of the messages to work, the message must be cached locally in the browser with local storage 

**Acceptance criteria:**
- [x] The user should optically recognize that his message is favored by a highlighted icon 
- [x] The favorite messages should be retained despite a restart or refresh of the website

**Complexity:**
m

**Tasks:**
- [x] Create new feature branch :sparkles: feature-local-storage :sparkles:
- [x] Add do lib directory 
- [x] fetch the data with useEffect 
- [x] Save to local storage
- [x] load from local storage
- [x] Toggle function on the favorite icon
