### ISSUE TITLE
Add a structured backend

### ISSUE THREAD

**Issue by bejanaf** [bejanaf/capstone-project#8]
**Value Statement:**
As a customer, I would like to see the latest news

**Description:**
The fetched messages require a backend, because they run over a private key so that it cannot be misused 

**Acceptance criteria:**
- [x] The user should transfer the fetched data to the backend, pass it on to the frontend (user story: news page) and get it displayed there
- [x] The user should not be able to find the API key

**Complexity:**
M

**Tasks:**
- [x] Create feature branch ✨ feature-backend ✨ 
- [x] Install express, cors, nodemon and concurrently
- [x] Modify package.json and .gitignore
- [x] Create a .env to secure the private key
- [x] Node fetch Data from the Api
- [x] Write a GET route to connect the backend with the frontend
- [x] Check the GET route with a fetch from the frontend
